baseURL = "http://mon.codes/"
languageCode = "en-us"
title = "Mon"
theme = "hugo-kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

#disqusShortname = "Mon"

# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    name = "Ramon"
    github = "ramondesc"
    #gitlab = "username"
    linkedin = "ramondesc"
    #facebook = "username"
    #twitter = "ds_says"
    #instagram = "username"
    stackoverflow = "ramondesc"
    #youtube = "user/username" # or channel/channelname

[params]
    tagline = "Explorando conceitos e ferramentas."
    description = "Kiera: A Hugo theme for creative and technical writing."
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    favicon = "/img/favicon.ico"
    #utterancesRepo = "https://github.com/MyRepo"
    #utterancesIssueTerm = "pathname"
    #homepageLength = 10

# uncomment to enable the Tags link on the main toolbar
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 1

# uncomment to enable the Categories link on the main toolbar
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 1